"""Application-wide configuration constants."""

# Audio
SAMPLE_RATE = 16000
BLOCK_SECONDS = 0.5
ENERGY_THRESHOLD = 0.003
SILENCE_BLOCKS_BEFORE_FLUSH = 3

# Models
PREVIEW_MODEL_PRIMARY = "medium"
PREVIEW_MODEL_FALLBACK = "small"
PRODUCTION_MODEL = "large"
DEVICE = "cuda"
FLOAT_PRECISION = "float16"
MODEL_NUM_WORKERS = 2
LANGUAGE = "fr"
PREVIEW_BEAM_SIZE = 3
PRODUCTION_BEAM_SIZE = 5
PREVIEW_VAD_FILTER = True
PRODUCTION_VAD_FILTER = True
PREVIEW_CONDITION_ON_PREVIOUS = False
PRODUCTION_CONDITION_ON_PREVIOUS = True
PREVIEW_WORD_TIMESTAMPS = False
PREVIEW_BEST_OF = 2
TEMPERATURE = 0.0

# Preview
PREVIEW_WINDOW_SECONDS = 3.0
PREVIEW_UPDATE_INTERVAL = 1.0
PREVIEW_TIMEOUT = 8.0

# Production
RESTORE_CLIPBOARD = True
PASTE_DELAY_SECONDS = 0.05
APPEND_SPACE = True

# Server
SSE_PORT = 5432
SSE_HOST = "127.0.0.1"

# Sleep / Hotkey
AUTO_SLEEP_SECONDS = 10.0
HOTKEY_TOGGLE = "alt gr+;"
HOTKEY_SEQUENCE_WINDOW = 0.6
TOGGLE_COOLDOWN_SECONDS = 0.8

# Visualizer
VISUALIZER_READY_DELAY = 2.5
VISUALIZER_START_DELAY = 2.0
VISUALIZER_STOP_TIMEOUT = 2.0
VISUALIZER_KILL_TIMEOUT = 1.0

# Misc
EXECUTOR_MAX_WORKERS = 2
